config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  resources :contents do
    member do
      get :favorite
      get :unfavorite
    end
    resources :comments, only: [ :create, :destroy ]
  end
  resources :users, only: [ :show ]
  resources :chatrooms, only: [ :show ] do
    resources :messages, only: :create
  end
end

app/models/content.rb
class Content < ApplicationRecord
  url = /[-a-zA-Z0-9@:%_\+.~#?&\/\/=]{2,256}\.[a-z]{2,4}\b(\/[-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)?/
  CATEGORIES = ["Natural", "Artificial", "Chemical treatment", "Protection"]
  STYLES = [ "Afro", "Bantu knots", "Dreadlocks", "Extensions",  "Faux locks", "Headscarves and Headwraps", "Jerry-curl", "Shaved", "S-curl", "Plaits", "Perms", "Weaves" ]
  CONTENT_TYPES = [ "Video", "Blog post" ]

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :blog_image
  has_many_attached :images

  acts_as_favoritable
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  validates :style, presence: true
  validates :content_type, presence: :true, inclusion: { in: CONTENT_TYPES }

  def thumbnail_url
    if video_url.present?
      key = video_url.split("/").last.split("=").last
      "https://i.ytimg.com/vi/#{key}/hqdefault.jpg"
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy, :favorite, :unfavorite]
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @contents = policy_scope(Content)
    if params[:query].present?
      sql_query = "title ILIKE :query
                  OR category ILIKE :query
                  OR style ILIKE :query
                  OR description ILIKE :query"
      @contents = @contents.where(sql_query, query:"%#{params[:query]}%")
    end
    if params[:category].present?
      @contents = @contents.where(category: params[:category])
      @filter = params[:category]
    end
    if params[:content].present?
      if params[:content][:style].present?
      @contents = @contents.where(style: params[:content][:style])
      @filter = params[:content][:style]
      end
    end
  end

  def show
    @comment = Comment.new
  end

  def new
    @content = Content.new
    authorize @content
  end

  def create
    @content = Content.new(content_params)
    @content.user = current_user

    @content.style = params[:content][:style].join(" ").lstrip
    authorize @content
    if @content.video_url.present?
      key = @content.video_url.split("/").last
      @content.video_url = "https://www.youtube.com/embed/#{key}"
    end
    if @content.save!
      redirect_to content_path(@content)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @content.update(content_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @content.destroy
    redirect_to dashboard_path
  end

  def favorite
    current_user.favorite(@content)
#     redirect_to contents_path(anchor: "content-#{@content.id}")
    respond_to do |format|
       format.html { redirect_to contents_path }
      format.js
    end
  end

  def unfavorite
    current_user.unfavorite(@content)
#     redirect_to contents_path(anchor: "content-#{@content.id}")
    respond_to do |format|
      format.html { redirect_to contents_path }
      format.js
  end
end
  private

  def content_params
    params.require(:content).permit(:title, :category, :description, :content_type, :blog_image, :video_url, :text)
  end

  def set_content
    @content = Content.find(params[:id])
    authorize @content
  end
end

app/views/contents/edit.html.erb
<div class="edit-page-container">
  <div class="photo-background">
    <div class="login-form" id="edit-form">
      <div class="simple-form-edit ml-4 mt-4 mr-4">
        <h2> Edit your upload </h2>
        <%= simple_form_for(@content) do |f| %>
          <%= f.input :title %>
          <%= f.input :description %>
          <%= f.input :text %>
          <%= f.input :photo, as: :file %>
          <%= f.input :category, as: :select, collection: ["Artificial", "Chemical treatment", "Natural", "Protection" ] %>
          <%= f.input :style, as: :select, collection: [ "Afro", "Bantu knots", "Dreadlocks", "Extensions",  "Faux locks", "Headscarves and Headwraps", "Jerry-curl", "S-curl", "Shaved", "Plaits", "Perms", "Weaves" ] %>
          <%= f.submit class: "btn btn-secondary", id: "edit-btn" %>
        <% end %>
        </div>
    </div>
  </div>
</div>

app/views/contents/favorite.js.erb
<%# const likeButton = document.getElementById('like-button');
likeButton.innerHTML = '<%= j render "contents/liked_link" %>
window.location.reload();

app/views/contents/index.html.erb
<div class="index-banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%= image_path "indexcover.jpg" %>);">

  <div class="search-form-control form-group" >
    <%= form_tag contents_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Please enter a style"
      %>
      <%= submit_tag "Search", class: "btn btn-secondary", id: "search-btn" %>
    <% end %>
  </div>
</div>
<%# <div class="pages-container2">
  <div class="container">
  </div>


</div> %>


<div class="index-card-container">
  <div class="filter-form">
    <%= render 'shared/filter' %>
  </div>


  <div class="all-cards" >
    <% @contents.each do |content| %>
      <div class="card" id="content<%= content.id %>">
        <% if content.user.profile_pic.attached? %>
            <%= cl_image_tag content.user.profile_pic.key, class: "indexcards" %>
        <% else %>
            <%= image_tag "placeholder.jpg" %>
        <% end %>

        <%= link_to content_path(content), class: "card-link" do %>

          <% if content.content_type == "Video" %>
            <img src="<%= content.thumbnail_url %>" class="thumb">
          <% elsif content.content_type == "Blog post" && content.blog_image.attached? %>
            <%= cl_image_tag content.blog_image.key, class: "thumb" %>
          <% end %>

          <div class="card-text">
            <h5><%= content.user.username %> | <%= content.content_type %></h5>
              <% if current_user&.favorited?(content) %>
                <%= link_to unfavorite_content_path(content), id:"unlike-button", remote: true do%>
                  <i class="fas fa-heart"></i>
                <% end %>
              <% elsif current_user %>
                  <%= link_to favorite_content_path(content), id:"like-button", remote: true do %>
                    <i class="far fa-heart"></i>
                <% end %>
              <% else %>
                <%= link_to new_user_session_path do %>
                  <i class="far fa-heart"></i>
              <% end %>
            <% end %>
            <div class="bottom-row">
              <%= link_to content_path(content), class: "card-link" do %>
              <span><%= content.title.capitalize %></span>
              <% end %>
            </div>
          </div>
          <!--
          <div class="tags">
            <strong><%= content.category %></strong> ||
            <%= content.style %>
          </div>
          -->
        <% end %>
      </div>
    <% end %>

  </div>

</div>

<div class="bottom-link">
  <%= link_to "Back to Top", contents_path%>
</div>

app/views/contents/new.html.erb
<div class="upload-form-image-background">
  <div class="upload-form">
    <h2 class="ml-4"> Teach A Style </h2>
    <form class="simple_form new_content" id="new_content" novalidate="novalidate" enctype="multipart/form-data" action="/contents" accept-charset="UTF-8" method="post">
      <input type="hidden" name="authenticity_token" value= "<%= form_authenticity_token %>">
      <div class="form-group string required content_title ml-4">
        <input class="form-control string required" type="text" name="content[title]" id="content_title" placeholder = "Title">
      </div>
      <div class="form-group text required content_description  ml-4">
        <textarea class="form-control text required" name="content[description]" id="content_description" placeholder = "Description"></textarea>
      </div>
      <fieldset class="radio_buttons required content_content_type">
        <div id="choices">
          <fieldset class="form-group radio_buttons optional content_content_type ml-4">
            <input type="hidden" name="content[content_type]" value="">
            <div class="form-check form-check-inline" id="content-new-check">
              <input class="content-type-input" type="radio" value="Blog post" name="content[content_type]" id="content_content_type_blog_post">
              <label class="content-type-label mb-0" for="content_content_type_blog_post">
              Blog post
              </label>
            </div>
            <div class="form-check form-check-inline" id="content-new-check">
            <input class="content-type-input" type="radio" value="Video" name="content[content_type]" id="content_content_type_video">
              <label class="content-type-label mb-0" for="content_content_type_video">
              Video
              </label>
            </div>
          </fieldset>
        </div>
        <div class="photo_input hidden">
          <div class="form-group file optional content_blog_image">
            <label class="file optional ml-4" for="content_blog_image"> 
            Blog image
            </label>
            <input class="form-control-file file optional ml-4" type="file" name="content[blog_image]" id="content_blog_image">
          </div>
          <div class="form-group text optional content_text">
            <label class="text optional ml-4" for="content_text">
            Write your blog down here!
            </label>
            <textarea class="form-control text optional ml-4" cols="5" rows="8" name="content[text]" wrap="hard" id="content_text"></textarea>
          </div>
        </div>
        <div class="video_input hidden ml-4">
          <p class="d-flex align-items-center mb-2 mt-2"> 
            Video URL
          <span type="button" data-toggle="modal" data-target="#exampleModalCenter">
              ?
          </span>
          </p>
          <div class="modal fade" data-backdrop="false" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content rodrigo">
                <div class="modal-header">
                  <h4 class="modal-title" id="exampleModalLongTitle">How to find your "embed" code on YouTube</h4>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <%= image_tag 'modal.png', class: "w-100"%>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
            <div class="form-group url optional content_video_url">
              <input class="form-control string url optional" placeholder="Insert URL here" type="url" name="content[video_url]" id="content_video_url">
            </div>
        </div>
      </fieldset>
      <div class="form-group select required content_category ml-4">
        <select class="form-control select required" name="content[category]" id="content_category">
          <option value="">Category</option>
          <option value="Artificial">Artificial</option>
          <option value="Chemical treatment">Chemical treatment</option>
          <option value="Natural">Natural</option>
          <option value="Protection">Protection</option>
        </select>
      </div>


      <div class="form-group">
        <label class="control-label check_boxes optional ml-4">Styles</label>
        <input type="hidden" name="content[style][]" value="">
        <div class="category-choices">
          <% Content::STYLES.each do |style| %>
            <input type="checkbox" class="hidden" value="<%= style %>" name="content[style][]" id="post_category_ids_<%= style %>">
            <label for="post_category_ids_<%= style %>" class="category-choice" style='background-image: url(<%=image_path "icons/#{style.downcase.gsub(' ', '_')}.jpg"%>)'>
              <span class="label-text"><%= style %></span>
            </label>
          <% end %>
        </div>
      </div>

      
      <input type="submit" name="commit" value="Upload" class="btn btn-outline-warning ml-4" data-disable-with="Create Content">
    </form>  
  </div>
</div>

app/views/contents/show.html.erb
<body style="background-color: whitesmoke;">

  <div id="show-container">
    <% if @content.video_url? %>
        <%= render 'shared/video_show'%>
    <% elsif @content.blog_image %>
      <%= render 'shared/blog_show' %>
    <% end %>

    <div class="comments comment-card">
      <h3 id="comments-title">Comments</h3>
      <% if @content.comments.blank? %>
        <p>Be the first to leave a comment :)</p>
      <% else %>
        <% @content.comments.each do |comment| %>
          <div class= "d-flex comment-box align-items-center mb-2">
            <% if comment.user.profile_pic.attached? %>
                <%= cl_image_tag comment.user.profile_pic.key, class: "comment-img" %>
            <% else %>
                <%= image_tag "placeholder.jpg" %>
            <% end %>

            <div class="d-block">
              <strong id="comment-username"><%= comment.user.username %></strong>
              <% if policy(comment).destroy? %>
                <%= link_to content_comment_path(@content, comment), method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
                  <i class="fas fa-trash" id="comment-bin"></i>
                <% end %>
              <% end %>
              <p class="m-0" id="comment-text"><%= comment.text %></p>
            </div>
          </div>
        <% end %>
      <% end %>
      <div class="comment-input">
        <%= simple_form_for [@content, @comment], remote: true do |f| %>
          <%= f.input :text, label: "Leave a comment" %>
        <%# <div class="form-actions btn"> %>
          <%= f.button :submit, "Submit", class: "btn btn-comment" %>
        <%#  </div> %>
        <% end %>
      </div>
    </div>
    <!--
    <div class="links">
      <% if policy(@content).update? %>
        <%= link_to 'Edit', edit_content_path(@content), class: "btn btn-secondary" %>
      <% end %>
    </div>
    -->
  </div>
</body>

app/views/contents/unfavorite.js.erb
window.location.reload();