config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  resources :contents do
    member do
      get :favorite
      get :unfavorite
    end
    resources :comments, only: [ :create, :destroy ]
  end
  resources :users, only: [ :show ]
  resources :chatrooms, only: [ :show ] do
    resources :messages, only: :create
  end
end

app/views/shared/_blog_show.html.erb
<div class="blog-show-container">
  <div class="blog-content">
    <div class="blog_text">
      <div id="blog-header">
        <h1><%= @content.title %></h1>
      </div>
      <div class="d-flex username-info align-items-center justify-content-between mb-2">
        <div class="creator-info d-flex align-items-center">
          <%= cl_image_tag @content.user.profile_pic.key, class: "comment-img" %>
          <h4><%= @content.user.username %></h4>
        </div>
        <div class="fav-heart d-flex align-items-center justify-content-between">
          <!-- favourite heart -->
          <% if current_user&.favorited?(@content) %>
            <%= link_to unfavorite_content_path(@content) do %>
              <i id="blog-like" class="fas fa-heart"></i>
            <% end %>
          <% elsif current_user %>
            <%= link_to favorite_content_path(@content), id:"like-button", remote: true do %>
              <i id="blog-like" class="far fa-heart"></i>
            <% end %>
          <% end %>
          <p class="fv-counter"><%= @content.favorited.count %></p>
        </div>
      </div>
      <div class="blog_banner d-flex justify-content-center">
        <%= cl_image_tag @content.blog_image.key, class:"blog-img" %> 
      </div>
      <div class="blog-description">
        <h3><%= @content.description %></h3>
      </div>
    </div>
    <div class="blog-text">
      <p> <%= @content.text %> </p>
    </div>
  </div>

</div>

app/views/shared/_blogs.html.erb
<div class="blog_show_container">
  <div class="blog-banner">
    <img src="<% @content.image %>">
  </div>
    <div class="blog-text">
      <h1><%= @content.title %></h1>
      <p><%= @content.description%></p>
      <p><%= @content.user%></p>
    </div>
  
</div>

app/views/shared/_favorite.js.erb
window.location.reload();

app/views/shared/_filter.html.erb
<%#= form_tag contents_path, method: :get do %>
  <%# <% Content::CATEGORIES.each do |category| %>
    <%# <div class="checkbox"> %>
      <%# <%= check_box_tag "category[]", category %>
      <%# <%= category %>
    <%# </div> %>
  <%# <% end %>
  <%# <%= submit_tag "Filter", class: "btn btn-secondary filter-btn" %>
<%# <% end %>
<!--
<form action="/contents" accept-charset="UTF-8" method="get">
    <div class="form-check2 form-check-inline checkbox">
      <input type="checkbox" name="category[]" id="category_" value="Natural" class="content-type-input hidden">
      <label class="content-type-label">
        Natural
      </label>
    </div> -->
<div class="sticky-filter" id="filter-fixed">
<h4 class="border-bottom border-secondary filter-header">CATEGORY</h4>
<form>
    <ul class="ks-cboxtags">
    <li><input type="checkbox" id="checkboxOne" name="category[]" id="category_" value="Natural"><label for="checkboxOne">Natural</label></li>
    <li><input type="checkbox" id="checkboxTwo" name="category[]" id="category_" value="Artificial"><label for="checkboxTwo">Artificial</label></li>
    <li><input type="checkbox" id="checkboxThree" name="category[]" id="category_" value="Chemical Treatment"><label for="checkboxThree">Chemical Treatment</label></li>
    <li><input type="checkbox" id="checkboxFour" name="category[]" id="category_" value="Protection"><label for="checkboxFour">Protection</label></li>
  </ul>
<!-- </form>
<form>
    <div class="checkbox">
      <input type="checkbox" name="category[]" id="category_" value="Natural">
      Natural
    </div>
    <div class="checkbox">
      <input type="checkbox" name="category[]" id="category_" value="Artificial">
      Artificial
    </div>
    <div class="checkbox">
      <input type="checkbox" name="category[]" id="category_" value="Chemical treatment">
      Chemical treatment
    </div>
    <div class="checkbox">
      <input type="checkbox" name="category[]" id="category_" value="Protection">
      Protection
    </div> -->
  <input type="submit" name="commit" value="Filter" class="btn btn-secondary filter-btn" data-disable-with="Filter" data-anchor="filter-fixed">
</form>

 <!--      <%= form_tag contents_path, method: :get do %>
      <h4>Filter by category</h4>
      <fieldset class="radio_buttons required content_content_type">
        <div id="category">
          <fieldset class="form-group radio_buttons optional content_content_type">
            <input type="hidden" name="category[]" value="">
            <div class="form-check2 form-check-inline">
              <input class="content-type-input hidden" type="radio" value="Natural" name="category[]">
              <label class="content-type-label">
              Natural
              </label>
            </div>
            <div class="form-check2 form-check-inline">
              <input class="content-type-input hidden" type="radio" value="Artificial" name="category[]">
              <label class="content-type-label">
              Artifical
              </label>
            </div>
            <div class="form-check2 form-check-inline">
              <input class="content-type-input hidden" type="radio" value="Chemical Treatment" name="category[]">
              <label class="content-type-label">
              Chemical Treatment
              </label>
            </div>
            <div class="form-check2 form-check-inline">
            <input class="content-type-input hidden" type="radio" value="Protection" name="category[]">
              <label class="content-type-label">
              Protection
              </label>
            </div>
          </fieldset>
        </div>
      </fieldset>
      <%= submit_tag "Filter", class: "btn btn-secondary filter-btn" %>
    <% end %>
 -->

<h4 class="border-bottom border-secondary filter-header">STYLE</h4>
<%= form_tag contents_path, method: :get do %>
   <div class="category-choices-index2">
      <% Content::STYLES.each do |style| %>
        <div class="vertical-choice">
          <input type="checkbox" class="hidden" value="<%= style %>" name="content[style][]" id="post_category_ids_<%= style %>">
          <label for="post_category_ids_<%= style %>" class="category-choice small-category-choice" style='background-image: url(<%=image_path "icons/#{style.downcase.gsub(' ', '_')}.jpg"%>); width: 60px; height: 60px; margin: 10px 10px 35px 0'>
          <p class="label-text1"> <%= style %> </p>
          </label>
          <!-- <span class="label-text"><%= style %></span> -->
          <!-- <p class="label-text1"> <%= style %> </p> -->
        </div>
      <% end %>
    </div>
  <%= submit_tag "Filter", class: "btn btn-secondary filter-btn", remote: true, anchor:"filter-fixed" %>
<% end %>

<!--
<h4>Filter by content type</h4>
<%= form_tag contents_path, method: :get do %>
  <% Content::CONTENT_TYPES.each do |content_type| %>
    <div class="checkbox">
      <%= check_box_tag "content_type[]", content_type %>
      <%= content_type %>
    </div>
  <% end %>
  <%= submit_tag "Filter", class: "btn btn-secondary filter-btn" %>
<% end %>
-->

<%= link_to 'All results', contents_path %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p class="footer-trademark mt-3 ml-3">TheHealthyHairHub™</p>
  <div class="links mr-3">
    <a href="https://twitter.com/thehealthyhair1" class="social"><i class="fab fa-twitter-square"></i></a>
    <a href="https://www.youtube.com/channel/UCWY5W6HVq_o08ZvjO63P9eQ" class="social"><i class="fab fa-youtube"></i></a>
    <a href="mailto:thehealthyhairhub@gmail.com" class="social"><i class="fab fa-google"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="height-nav navbar navbar-expand-sm navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "THHH-Logo-White.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'BROWSE', contents_path, class: "nav-links" %>
        </li>
        <li class="nav-item">
          <%= link_to 'FORUMS', chatroom_path(Chatroom.first), class: "nav-links" %>
        </li>
        <li class="nav-item">
          <%= link_to 'DASHBOARD', dashboard_path, class: "nav-links" %>
        </li>

        <li class="nav-item dropdown pl-2">
          <% if current_user.profile_pic.attached? %>

           <%= cl_image_tag current_user.profile_pic.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "placeholder.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Upload content", new_content_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_video_show.html.erb
<div class="video-show-container">

  <div class="vid-header">
    <h1><%= @content.title %></h1>
  </div>

  <div class="vid-content-container">
    <div class="video">
      <iframe width="560" height="315" src="<%= @content.video_url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <div class="vid-user">
        <div class="v-user-av">
          <% if @content.user.profile_pic.attached? %>
              <%= cl_image_tag @content.user.profile_pic.key, class: "avatar" %>
          <% else %>
              <%= image_tag "placeholder.jpg" %>
          <% end %>
          <p><%= @content.user.username %></p>
        </div>
        <% if current_user&.favorited?(@content) %>
          <%= link_to unfavorite_content_path(@content) do %>
          <i class="fas fa-heart" id="video-like"></i><%= @content.favorited.count %>
          <% end %>
        <% elsif current_user %>
          <%= link_to favorite_content_path(@content), id:"like-button", remote: true do %>
          <i class="far fa-heart" id="video-like"></i><%= @content.favorited.count %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="vid-text">
      <p><%= @content.description%></p>
    </div>
  </div>
  
</div>