config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  resources :contents do
    member do
      get :favorite
      get :unfavorite
    end
    resources :comments, only: [ :create, :destroy ]
  end
  resources :users, only: [ :show ]
  resources :chatrooms, only: [ :show ] do
    resources :messages, only: :create
  end
end

app/views/pages/dashboard.html.erb
<div class="dashboard-images">
  <div class="row2">
    <div class="column2" id="col-1">
      <%= image_tag 'leather.jpg', class: "col-sm" %>
    </div>
    <div class="column2">
      <%= image_tag 'headscarf.jpg', class: "col-sm"  %>
    </div>
    <div class="column2">
      <%= image_tag 'short.jpg', class: "col-sm"  %>
    </div>
  </div>
</div>

<div class="dashboard-container">

  <div class="all-dash-col">

    <div class="dash-col" id="profilecard">
      <div class="card-category" id="profile-heading">
        <p>Profile</p>
      </div>
      <div class="profilecardsticky">
        <br>
        <% if current_user.profile_pic.attached? %>
            <%= cl_image_tag current_user.profile_pic.key, class: "profilecardimage"%>
        <% else %>
            <%= image_tag "placeholder.jpg" %>
        <% end %>
        <h3 id="username"><%= current_user.username %></h3>
        <div class="dashboard-links">
          <%= link_to 'Upload new content', new_content_path, id: "btn-upload" %>
        </div>
      </div>
    </div>

    <div class="dash-col" id="my-uploads">
      <div class="card-category" id="uploads-heading">
        <p>Uploads</p>
      </div>
        <!-- Uploads iterator -->
      <% if current_user.contents.empty? %>
        <p id="p-text">No uploads yet</p>
      <% else %>
        <% current_user.contents.each do |content| %>

          <div class="card-product">
            <%= link_to content_path(content) do %>

              <% if content.content_type == "Video"%>
                <img src=<%= content.thumbnail_url%> >
              <% elsif content.content_type == "Blog post" && content.blog_image.attached?%>
                <%= cl_image_tag content.blog_image.key, width: 300 %>
              <% end %>

              <div class="card-product-infos">
                <h4><%= content.title %></h4>
                <p><em>Uploaded by <strong> you </strong></em></p>
                <div class="links">
                  <p>
                    <% if policy(content).update? %>
                      <%= link_to edit_content_path(content) do %>
                      <i class="far fa-edit dashboard-icon"></i>
                      <% end %>
                    <% end %>
                  </p>
                  <p>
                    <% if policy(content).destroy? %>
                      <%= link_to content, method: :delete, data: { confirm: 'Are you sure?' } do %>
                        <i class="fas fa-trash dashboard-icon"></i>
                      <% end%>
                    <% end %>
                  </p>
                </div>
              </div>

            <% end %>
          </div>

        <% end %>
      <% end %>
    </div>

    <div class="dash-col" id="my-favourites">
      <div class="card-category" id="favourites-heading">
        <p>Favourites</p>
      </div>
      <!-- Favourites iterator -->
      <% if current_user.favorites.empty?%>
        <p id="p-text">No favourites yet</p>
      <% else %>

        <% current_user.favorites.each do |favorite| %>

          <div class="card-product">
            <%= link_to content_path(favorite) do %>

              <% if favorite.favoritable.content_type == "Video"%>
                <img src=<%= favorite.favoritable.thumbnail_url%> >
              <% elsif favorite.favoritable.content_type == "Blog post" && favorite.favoritable.blog_image.attached?%>
                <%= cl_image_tag favorite.favoritable.blog_image.key, width: 300 %>
              <% end %>

              <div class="card-product-infos">
                <h4><%= favorite.favoritable.title %></h4>
                <p><em>Uploaded by <strong> <%= favorite.favoritable.user.username %> </strong></em></p>

                <div class="links">
                  <p>
                    <%= link_to unfavorite_content_path(favorite) do %>
                      <i class="fas fa-heart" id="small-heart"></i>
                    <% end %>
                  </p>
                </div>
              </div>

            <% end %>
          </div>

        <% end %>

      <% end %>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<% content_for :meta_title, "The Healthy Hair Hub - A community for styling Afro-Caribbean hair" %>
<% content_for :meta_description, "We share tips and tricks to help you learn to take care of your hair at home" %>
<% content_for :meta_image, "cover.png" %>

<div class= "homepage">
  <h1 class="home-h1"><%= image_tag 'THHH-Logo-Blue.png'%></h1>
  <%= link_to "Enter Site", contents_path, class: "btn home-button" %>


 <div class="carousel-group">
    <div class="carousel-container">


      <div id="carouselExampleIndicators" class="carousel-slide" data-ride="carousel" data-interval="8000">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active" style=" height: 100vh;" >
            <%= image_tag 'braid.jpg', class: "slide-image"%>
              <div class="carousel-caption">
                <h5></h5>
                <p></p>
              </div>
          </div>
          <div class="carousel-item" style=" height: 100vh;" >
            <%= image_tag 'red.jpg', class: "slide-image"%>
              <div class="carousel-caption" class="text-left">
                <h5></h5>
                <p></p>
              </div>
          </div>
          <div class="carousel-item" style=" height: 100vh;" >
            <%= image_tag 'eyesclosed.jpg', class: "slide-image"%>
              <div class="carousel-caption">
                <h5></h5>
                <p></p>
              </div>
          </div>
          <div class="carousel-item" style=" height: 100vh;" >
            <%= image_tag 'man&woman.jpg', class: "slide-image"%>
              <div class="carousel-caption" class="text-left">
                <h5></h5>
                <p></p>
              </div>
          </div>
        </div>
      </div>


      <div id="carouselExampleIndicators" class="carousel-slide" data-ride="carousel" data-interval="8000">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active" style=" height: 100vh;" >
            <%= image_tag 'headscarf.jpg', class: "slide-image"%>
              <div class="carousel-caption">
                <h5></h5>
                <p></p>
              </div>
          </div>
          <div class="carousel-item" style=" height: 100vh;" >
            <%= image_tag 'afrowind.jpg', class: "slide-image"%>
              <div class="carousel-caption" class="text-left">
                <h5></h5>
                <p></p>
              </div>
          </div>
          <div class="carousel-item" style=" height: 100vh;" >
            <%= image_tag 'short.jpg', class: "slide-image"%>
              <div class="carousel-caption">
                <h5></h5>
                <p></p>
              </div>
          </div>
          <div class="carousel-item" style=" height: 100vh;" >
            <%= image_tag 'necklace.jpg', class: "slide-image"%>
              <div class="carousel-caption" class="text-left">
                <h5></h5>
                <p></p>
              </div>
          </div>
        </div>
      </div>


      <div id="carouselExampleIndicators" class="carousel-slide" data-ride="carousel" data-interval="8000">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active" style=" height: 100vh;" >
            <%= image_tag 'field.jpg', class: "slide-image"%>
              <div class="carousel-caption">
                <h5></h5>
                <p></p>
              </div>
          </div>
          <div class="carousel-item" style=" height: 100vh;" >
            <%= image_tag 'wall.jpg', class: "slide-image"%>
              <div class="carousel-caption" class="text-left">
                <h5></h5>
                <p></p>
              </div>
          </div>
          <div class="carousel-item" style=" height: 100vh;">
            <%= image_tag 'dreadlocks.jpg', class: "slide-image"%>
              <div class="carousel-caption">
                <h5></h5>
                <p></p>
              </div>
          </div>
          <div class="carousel-item" style=" height: 100vh;" >
            <%= image_tag 'leather.jpg', class: "slide-image"%>
              <div class="carousel-caption" class="text-left">
                <h5></h5>
                <p></p>
              </div>
          </div>
        </div>
      </div>




      </div>
    </div>
  </div>